#!/usr/bin/env python3
# from typing import *



# def solve(N: int, M: int, T: List[int], P: List[int], Q: int, A: List[int], B: List[int]) -> List[str]:
def solve(N, M, T, P, Q, A, B):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    T = [None for _ in range(M)]
    P = [None for _ in range(M)]
    for i in range(M):
        T[i], P[i] = map(int, input().split())
    Q = int(input())
    A = [None for _ in range(Q)]
    B = [None for _ in range(Q)]
    for i in range(Q):
        A[i], B[i] = map(int, input().split())
    a = solve(N, M, T, P, Q, A, B)
    for i in range(Q):
        print(a[i])

if __name__ == '__main__':
    main()
