#!/usr/bin/env python3
# from typing import *


# def solve(a: int, b: int, x: int) -> float:
def solve(a, b, x):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a, b, x = map(int, input().split())
    a1 = solve(a, b, x)
    print(a1)


if __name__ == '__main__':
    main()
