#!/usr/bin/env python3
# from typing import *



# def solve(N: int, M: int, A: List[int], U: List[int], V: List[int], B: List[int]) -> List[str]:
def solve(N, M, A, U, V, B):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    M = int(next(tokens))
    A = [None for _ in range(N)]
    U = [None for _ in range(M)]
    V = [None for _ in range(M)]
    B = [None for _ in range(M)]
    for i in range(N):
        A[i] = int(next(tokens))
    for i in range(M):
        U[i] = int(next(tokens))
        V[i] = int(next(tokens))
        B[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, M, A, U, V, B)
    print(*[a[i] for i in range(N)])

if __name__ == '__main__':
    main()
