#!/usr/bin/env python3
# from typing import *



# def solve(S: str, T: str) -> Tuple[str, List[str]]:
def solve(S, T):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    T = input()
    n, a = solve(S, T)
    print(n)
    for i in range(n):
        print(a[i])

if __name__ == '__main__':
    main()
