#!/usr/bin/env python3
# from typing import *


# def solve(N: int, X: int, Y: int, U: List[int], V: List[int]) -> Tuple[List[str], List[str]]:
def solve(N, X, Y, U, V):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, X, Y = map(int, input().split())
    U = [None for _ in range(N - 1)]
    V = [None for _ in range(N - 1)]
    for i in range(N - 1):
        U[i], V[i] = map(int, input().split())
    a, d = solve(N, X, Y, U, V)
    for i in range(X):
        print(a[i], end=' ')
        print(d[i], end=' ')
    print()


if __name__ == '__main__':
    main()
