#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(N: str, Q: str, S: str, query: List[str]) -> Any:
def solve(N, Q, S, query):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, Q = input().split()
    query = [None for _ in range(Q)]
    S = input()
    for i in range(Q):
        query[i] = input()
    ans = solve(N, Q, S, query)
    print(ans)  # TODO: edit here

if __name__ == '__main__':
    main()
