#!/usr/bin/env python3
# from typing import *



# def solve(L: int, Q: int, c: List[int], x: List[int]) -> Any:
def solve(L, Q, c, x):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    L, Q = map(int, input().split())
    c = [None for _ in range(Q)]
    x = [None for _ in range(Q)]
    for i in range(Q):
        c[i], x[i] = map(int, input().split())
    ans = solve(L, Q, c, x)
    print(ans)  # TODO: edit here

if __name__ == '__main__':
    main()
