#!/usr/bin/env python3
# from typing import *

MOD = 998244353

# def solve(R: int) -> int:
def solve(R):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    R = int(input())
    a = solve(R)
    print(a)

if __name__ == '__main__':
    main()
