#!/usr/bin/env python3
# from typing import *



# def solve(N: int, T: int, c: List[int], t: List[int]) -> str:
def solve(N, T, c, t):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, T = map(int, input().split())
    c = [None for _ in range(N)]
    t = [None for _ in range(N)]
    for i in range(N):
        c[i], t[i] = map(int, input().split())
    a = solve(N, T, c, t)
    print(a)

if __name__ == '__main__':
    main()
