#!/usr/bin/env python3
# from typing import *



# def solve(N: int, C: int, s: List[int], t: List[int], c: List[int]) -> int:
def solve(N, C, s, t, c):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, C = map(int, input().split())
    s = [None for _ in range(N)]
    t = [None for _ in range(N)]
    c = [None for _ in range(N)]
    for i in range(N):
        s[i], t[i], c[i] = map(int, input().split())
    a = solve(N, C, s, t, c)
    print(a)

if __name__ == '__main__':
    main()
