#!/usr/bin/env python3
# from typing import *

MOD = 998244353


# def solve(N: int, A: int, B: int, P: int, Q: int) -> int:
def solve(N, A, B, P, Q):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, A, B, P, Q = map(int, input().split())
    a = solve(N, A, B, P, Q)
    print(a)


if __name__ == '__main__':
    main()
