#!/usr/bin/env python3
# from typing import *



# def solve(a: int, b: int, c: int, d: int, e: int, f: int, g: int, h: int, m: int, n: int) -> List[str]:
def solve(a, b, c, d, e, f, g, h, m, n):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = int(input())
    b, c, d = map(int, input().split())
    e, f, g = map(int, input().split())
    h, m, n = map(int, input().split())
    o = solve(a, b, c, d, e, f, g, h, m, n)
    for i in range(a):
        print(o[i])

if __name__ == '__main__':
    main()
