#!/usr/bin/env python3
# from typing import *


# def solve(N: int, M: int, a: List[int], b: List[int], Q: int, x: List[int], k: List[int]) -> Tuple[str, List[str]]:
def solve(N, M, a, b, Q, x, k):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    a = [None for _ in range(M)]
    b = [None for _ in range(M)]
    for i in range(M):
        a[i], b[i] = map(int, input().split())
    Q = int(input())
    x = [None for _ in range(Q)]
    k = [None for _ in range(Q)]
    for i in range(Q):
        x[i], k[i] = map(int, input().split())
    d, f = solve(N, M, a, b, Q, x, k)
    print(d)
    for i in range(N):
        print(f[i])


if __name__ == '__main__':
    main()
