#!/usr/bin/env python3
# from typing import *



# def solve(H: int, W: int, S: List[str], A: int, B: int, C: int, D: int) -> int:
def solve(H, W, S, A, B, C, D):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    H, W = map(int, input().split())
    S = [None for _ in range(H)]
    for i in range(H):
        S[i] = input()
    A, B, C, D = map(int, input().split())
    a = solve(H, W, S, A, B, C, D)
    print(a)

if __name__ == '__main__':
    main()
