#!/usr/bin/env python3
# from typing import *



# def solve(N: int, T: int, P: int, L: List[int]) -> int:
def solve(N, T, P, L):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    T = int(next(tokens))
    P = int(next(tokens))
    L = [None for _ in range(N)]
    for i in range(N):
        L[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, T, P, L)
    print(a)

if __name__ == '__main__':
    main()
