#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(V: int, T: int, S: int, D: int) -> str:
def solve(V, T, S, D):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    V, T, S, D = map(int, input().split())
    a = solve(V, T, S, D)
    print(a)

if __name__ == '__main__':
    main()
