#!/usr/bin/env python3
# from typing import *



# def solve(A: int, B: int, H: int, M: int) -> float:
def solve(A, B, H, M):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A, B, H, M = map(int, input().split())
    a = solve(A, B, H, M)
    print(a)

if __name__ == '__main__':
    main()
