#!/usr/bin/env python3
# from typing import *


# def solve(N: int, A: int, X: int, Y: int) -> float:
def solve(N, A, X, Y):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, A, X, Y = map(int, input().split())
    a = solve(N, A, X, Y)
    print(a)


if __name__ == '__main__':
    main()
