#!/usr/bin/env python3
# from typing import *


# def solve(a: str, b: List[str], c: List[str], d: List[str]) -> Tuple[str, List[str], List[str]]:
def solve(a, b, c, d):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = input()
    b = [None for _ in range(a)]
    c = [None for _ in range(a)]
    d = [None for _ in range(a)]
    for i in range(a):
        b[i], c[i], d[i] = input().split()
    a, b, c = solve(a, b, c, d)
    print(a)
    for i in range(a):
        print(b[i])
        print(c[i])


if __name__ == '__main__':
    main()
