#!/usr/bin/env python3
# from typing import *


# def solve(N: int, Q: int, x: List[int]) -> List[str]:
def solve(N, Q, x):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, Q = map(int, input().split())
    x = [None for _ in range(Q)]
    for i in range(Q):
        x[i] = int(input())
    ans = solve(N, Q, x)
    print(*[ans[i] for i in range(N)])


if __name__ == '__main__':
    main()
