#!/usr/bin/env python3
# from typing import *



# def solve(A: int, M: int, L: int, R: int) -> int:
def solve(A, M, L, R):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A, M, L, R = map(int, input().split())
    a = solve(A, M, L, R)
    print(a)

if __name__ == '__main__':
    main()
