#!/usr/bin/env python3
# from typing import *



# def solve(N: int, M: int, u: List[int], v: List[int], w: List[int]) -> List[str]:
def solve(N, M, u, v, w):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    u = [None for _ in range(M)]
    v = [None for _ in range(M)]
    w = [None for _ in range(M)]
    for i in range(M):
        u[i], v[i], w[i] = map(int, input().split())
    ans = solve(N, M, u, v, w)
    print(*[ans[i] for i in range(N)])

if __name__ == '__main__':
    main()
