#!/usr/bin/env python3
# from typing import *


# def solve(H: int, M: int) -> Tuple[int, int]:
def solve(H, M):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    H, M = map(int, input().split())
    h, m = solve(H, M)
    print(h, m)


if __name__ == '__main__':
    main()
