#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(N: int, T: int, A: int) -> str:
def solve(N, T, A):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, T, A = map(int, input().split())
    a = solve(N, T, A)
    print(a)

if __name__ == '__main__':
    main()
