#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(N: str, M: str, L: List[str], R: List[str], D: List[str]) -> str:
def solve(N, M, L, R, D):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = input().split()
    L = [None for _ in range(M)]
    R = [None for _ in range(M)]
    D = [None for _ in range(M)]
    for i in range(M):
        L[i], R[i], D[i] = input().split()
    a = solve(N, M, L, R, D)
    print(a)


if __name__ == '__main__':
    main()
