#!/usr/bin/env python3
# from typing import *


# def solve(N: int, T: str, S: List[str]) -> int:
def solve(N, T, S):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    T = next(tokens)
    S = [None for _ in range(N)]
    for i in range(N):
        S[i] = next(tokens)
    assert next(tokens, None) is None
    a = solve(N, T, S)
    print(a)


if __name__ == '__main__':
    main()
