#!/usr/bin/env python3
# from typing import *


# def solve(A: int, B: int, W: int) -> List[str]:
def solve(A, B, W):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A, B, W = map(int, input().split())
    a = solve(A, B, W)
    print(*[a[i] for i in range(W)])


if __name__ == '__main__':
    main()
