#!/usr/bin/env python3
# from typing import *



# def solve(N: int, A: List[int]) -> List[str]:
def solve(N, A):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    A = [None for _ in range(N)]
    for i in range(N):
        A[i] = int(input())
    ans = solve(N, A)
    for i in range(N):
        print(ans[i])

if __name__ == '__main__':
    main()
