#!/usr/bin/env python3
# from typing import *



# def solve(H: str, W: str, M: str, X: List[str], Y: List[str]) -> int:
def solve(H, W, M, X, Y):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    H, W, M = input().split()
    X = [None for _ in range(M)]
    Y = [None for _ in range(M)]
    for i in range(M):
        X[i], Y[i] = input().split()
    a = solve(H, W, M, X, Y)
    print(a)

if __name__ == '__main__':
    main()
