#!/usr/bin/env python3
# from typing import *



# def solve(P: int, Q: int, R: int) -> int:
def solve(P, Q, R):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    P, Q, R = map(int, input().split())
    a = solve(P, Q, R)
    print(a)

if __name__ == '__main__':
    main()
