#!/usr/bin/env python3
# from typing import *



# def solve(N: int, D: int, P: int, F: List[int]) -> int:
def solve(N, D, P, F):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    D = int(next(tokens))
    P = int(next(tokens))
    F = [None for _ in range(N)]
    for i in range(N):
        F[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, D, P, F)
    print(a)

if __name__ == '__main__':
    main()
