#!/usr/bin/env python3
# from typing import *



# def solve(S: str, Q: int, K: List[int]) -> List[str]:
def solve(S, Q, K):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    S = next(tokens)
    Q = int(next(tokens))
    K = [None for _ in range(Q)]
    for i in range(Q):
        K[i] = int(next(tokens))
    assert next(tokens, None) is None
    C = solve(S, Q, K)
    print(*[C[i] for i in range(Q)])

if __name__ == '__main__':
    main()
