#!/usr/bin/env python3
# from typing import *

MOD = 998244353


# def solve(A: int, B: int, C: int, D: int, E: int, F: int) -> int:
def solve(A, B, C, D, E, F):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A, B, C, D, E, F = map(int, input().split())
    a = solve(A, B, C, D, E, F)
    print(a)


if __name__ == '__main__':
    main()
