#!/usr/bin/env python3
# from typing import *



# def solve(a: int, b: int, c: int, d: int, e: int) -> Tuple[float, float]:
def solve(a, b, c, d, e):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = int(input())
    b, c = map(int, input().split())
    d, e = map(int, input().split())
    h, m = solve(a, b, c, d, e)
    print(h, m)

if __name__ == '__main__':
    main()
