#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(a: int, b: int, c: int, d: int, e: int, f: int, g: int, h: int, i: int, j: int, k: int, l: int) -> str:
def solve(a, b, c, d, e, f, g, h, i, j, k, l):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a, b, c, d, e, f = map(int, input().split())
    g, h, i, j, k, l = map(int, input().split())
    a1 = solve(a, b, c, d, e, f, g, h, i, j, k, l)
    print(a1)

if __name__ == '__main__':
    main()
