#!/usr/bin/env python3
# from typing import *



# def solve(N: str, M: str, A: List[List[str]]) -> Tuple[int, int, int, int]:
def solve(N, M, A):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = next(tokens)
    M = next(tokens)
    A = [[None for _ in range(M + 2 * N + 4)] for _ in range(M + 2 * N + 4)]
    for j in range(2 * N + 4):
        for i in range(M):
            A[i + j][i + j] = next(tokens)
    assert next(tokens, None) is None
    a, b, c, d = solve(N, M, A)
    print(a)
    print(b)
    print(c)
    print(d)

if __name__ == '__main__':
    main()
