#!/usr/bin/env python3
# from typing import *


# def solve(N: int, A: int, B: int) -> Any:
def solve(N, A, B):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, A, B = map(int, input().split())
    ans = solve(N, A, B)
    print(ans)  # TODO: edit here


if __name__ == '__main__':
    main()
