#!/usr/bin/env python3
# from typing import *


# def solve(S: str, T: str, A: int, B: int, U: str) -> Tuple[int, int]:
def solve(S, T, A, B, U):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S, T = input().split()
    A, B = map(int, input().split())
    U = input()
    c, d = solve(S, T, A, B, U)
    print(c, d)


if __name__ == '__main__':
    main()
