#!/usr/bin/env python3
# from typing import *



# def solve(sx: int, sy: int, tx: int, ty: int) -> str:
def solve(sx, sy, tx, ty):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    sx, sy, tx, ty = map(int, input().split())
    a = solve(sx, sy, tx, ty)
    print(a)

if __name__ == '__main__':
    main()
