#!/usr/bin/env python3
# from typing import *



# def solve(S: str, K: int) -> str:
def solve(S, K):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    S = next(tokens)
    K = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(S, K)
    print(a)

if __name__ == '__main__':
    main()
