#!/usr/bin/env python3
# from typing import *


# def solve(A: int, B: int, N: int) -> int:
def solve(A, B, N):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A, B, N = map(int, input().split())
    a = solve(A, B, N)
    print(a)


if __name__ == '__main__':
    main()
