#!/usr/bin/env python3
# from typing import *

MOD = 998244353

# def solve(N: int, P: int) -> Any:
def solve(N, P):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, P = map(int, input().split())
    ans = solve(N, P)
    print(ans)  # TODO: edit here

if __name__ == '__main__':
    main()
