#!/usr/bin/env python3
# from typing import *



# def solve(a: int, b: List[int], c: List[int], d: int, e: List[int]) -> List[str]:
def solve(a, b, c, d, e):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = int(input())
    b = [None for _ in range(a)]
    c = [None for _ in range(a)]
    for i in range(a):
        b[i], c[i] = map(int, input().split())
    d = int(input())
    e = [None for _ in range(d)]
    for i in range(d):
        e[i] = int(input())
    f = solve(a, b, c, d, e)
    for i in range(d):
        print(f[i])

if __name__ == '__main__':
    main()
