#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(P: int, a: int, b: int) -> List[str]:
def solve(P, a, b):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    P, a, b = map(int, input().split())
    A = solve(P, a, b)
    print(*[A[i] for i in range(P)])

if __name__ == '__main__':
    main()
