#!/usr/bin/env python3
# from typing import *



# def solve(R: int, C: int) -> str:
def solve(R, C):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    R, C = map(int, input().split())
    a = solve(R, C)
    print(a)

if __name__ == '__main__':
    main()
