#!/usr/bin/env python3
# from typing import *



# def solve(abc: int) -> int:
def solve(abc):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    abc = int(input())
    a = solve(abc)
    print(a)

if __name__ == '__main__':
    main()
