#!/usr/bin/env python3
# from typing import *



# def solve(N: int, K: int, A: List[int]) -> int:
def solve(N, K, A):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, K = map(int, input().split())
    A = [None for _ in range(N)]
    for i in range(N):
        A[i] = int(input())
    a = solve(N, K, A)
    print(a)

if __name__ == '__main__':
    main()
