#!/usr/bin/env python3
# from typing import *



# def solve(N: str, M: str, S: List[List[str]], T: List[List[str]]) -> Tuple[int, int]:
def solve(N, M, S, T):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = next(tokens)
    M = next(tokens)
    S = [[None for _ in range(2 * N + 4)] for _ in range(2 * N + 4)]
    T = [[None for _ in range(2 * M + 4)] for _ in range(2 * M + 4)]
    for j in range(N + 4):
        for i in range(N):
            S[i + j][i + j] = next(tokens)
    for j in range(M + 4):
        for i in range(M):
            T[i + j][i + j] = next(tokens)
    assert next(tokens, None) is None
    a, b = solve(N, M, S, T)
    print(a, b)

if __name__ == '__main__':
    main()
