#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(s: str, x: int, y: int) -> str:
def solve(s, x, y):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    s = input()
    x, y = map(int, input().split())
    a = solve(s, x, y)
    print(a)


if __name__ == '__main__':
    main()
