#!/usr/bin/env python3
# from typing import *


# def solve(N: int, A: List[int], B: List[int], Q: int, U: List[int], K: List[int]) -> Any:
def solve(N, A, B, Q, U, K):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    A = [None for _ in range(N - 1)]
    B = [None for _ in range(N - 1)]
    for i in range(N - 1):
        A[i], B[i] = map(int, input().split())
    Q = int(input())
    U = [None for _ in range(Q)]
    K = [None for _ in range(Q)]
    for i in range(Q):
        U[i], K[i] = map(int, input().split())
    ans = solve(N, A, B, Q, U, K)
    print(ans)  # TODO: edit here


if __name__ == '__main__':
    main()
