#!/usr/bin/env python3
# from typing import *


# def solve(N: str, K: int) -> int:
def solve(N, K):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = input()
    K = int(input())
    a = solve(N, K)
    print(a)


if __name__ == '__main__':
    main()
