#!/usr/bin/env python3
# from typing import *



# def solve(C: str) -> str:
def solve(C):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    C = input()
    a = solve(C)
    print(a)

if __name__ == '__main__':
    main()
