#!/usr/bin/env python3
# from typing import *

MOD = 998244353

# def solve(N: str, P: List[str]) -> Any:
def solve(N, P):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = next(tokens)
    P = [None for _ in range(N - 1)]
    for i in range(N - 1):
        P[i] = next(tokens)
    assert next(tokens, None) is None
    ans = solve(N, P)
    print(ans)  # TODO: edit here

if __name__ == '__main__':
    main()
