#!/usr/bin/env python3
# from typing import *

MOD = 1000000007

# def solve(L: int) -> int:
def solve(L):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    L = int(input())
    a = solve(L)
    print(a)

if __name__ == '__main__':
    main()
