#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(N: str, K: str, u: List[str], v: List[str]) -> str:
def solve(N, K, u, v):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    u = [None for _ in range(NK - 1)]
    v = [None for _ in range(NK - 1)]
    N, K = input().split()
    for i in range(NK - 1):
        u[i], v[i] = input().split()
    a = solve(N, K, u, v)
    print(a)

if __name__ == '__main__':
    main()
