#!/usr/bin/env python3
# from typing import *


# def solve(s: str) -> Tuple[int, int]:
def solve(s):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    s = input()
    c, d = solve(s)
    print(c, d)


if __name__ == '__main__':
    main()
