#!/usr/bin/env python3
# from typing import *

MOD = 998244353

# def solve(N: int, M: int, S: str) -> Tuple[List[str], str]:
def solve(N, M, S):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    S = input()
    c, d = solve(N, M, S)
    print(*[c[i] for i in range(N)], d)

if __name__ == '__main__':
    main()
