#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py' number_of_test_cases_you_want
import random

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 3)  # TODO: edit here
    A = [None for _ in range(N)]
    B = [None for _ in range(N)]
    for i in range(N):
        A[i] = random.randint(1,1e9)  # TODO: edit here
        B[i] = random.randint(1,1e9)  # TODO: edit here
    print(N)
    # print(*[A[i], B[i] for i in range(N)])
    for i in range(N):
        print(A[i], end=" ")
        print(B[i])

if __name__ == "__main__":
    main()
