#!/usr/bin/env python3
# from typing import *


# def solve(N: int, A: List[int], B: List[int]) -> Tuple[List[str], List[str], str]:
def solve(N, A, B):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    A = [None for _ in range(N - 1)]
    B = [None for _ in range(N - 1)]
    for i in range(N - 1):
        A[i], B[i] = map(int, input().split())
    d, e, f = solve(N, A, B)
    for i in range(N):
        print(d[i], end=' ')
        print(e[i], end=' ')
    print(f)


if __name__ == '__main__':
    main()
