#!/usr/bin/env python3
# from typing import *



# def solve(N: int, C: int, a: List[int], b: List[int], c: List[int]) -> int:
def solve(N, C, a, b, c):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, C = map(int, input().split())
    a = [None for _ in range(N)]
    b = [None for _ in range(N)]
    c = [None for _ in range(N)]
    for i in range(N):
        a[i], b[i], c[i] = map(int, input().split())
    a1 = solve(N, C, a, b, c)
    print(a1)

if __name__ == '__main__':
    main()
