#!/usr/bin/env python3
# from typing import *



# def solve(s: str) -> Tuple[str, str, str]:
def solve(s):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    s = input()
    d, e, f = solve(s)
    print(d, e, f)

if __name__ == '__main__':
    main()
