#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(N: int, M: int, X: List[int], Y: List[int], C: List[str]) -> str:
def solve(N, M, X, Y, C):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    M = int(next(tokens))
    X = [None for _ in range(M)]
    Y = [None for _ in range(M)]
    C = [None for _ in range(M)]
    for i in range(M):
        X[i] = int(next(tokens))
        Y[i] = int(next(tokens))
        C[i] = next(tokens)
    assert next(tokens, None) is None
    a = solve(N, M, X, Y, C)
    print(a)

if __name__ == '__main__':
    main()
