#!/usr/bin/env python3
# from typing import *



# def solve(a: str, b: List[str], c: List[List[str]]) -> int:
def solve(a, b, c):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    a = next(tokens)
    b = [None for _ in range(a)]
    c = [[None for _ in range(a)] for _ in range(a)]
    for i in range(a):
        b[i] = next(tokens)
        for j in range(i):
            c[i][j] = next(tokens)
    assert next(tokens, None) is None
    a1 = solve(a, b, c)
    print(a1)

if __name__ == '__main__':
    main()
