#!/usr/bin/env python3
# from typing import *

MOD = 998244353


# def solve(W: int, K: int, w: List[int]) -> Any:
def solve(W, K, w):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    W = int(next(tokens))
    K = int(next(tokens))
    w = [None for _ in range(K)]
    for i in range(K):
        w[i] = int(next(tokens))
    assert next(tokens, None) is None
    ans = solve(W, K, w)
    print(ans)  # TODO: edit here


if __name__ == '__main__':
    main()
