#!/usr/bin/env python3
# from typing import *



# def solve(AtCoder: str, s: str, Contest: str) -> str:
def solve(AtCoder, s, Contest):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    AtCoder, s, Contest = input().split()
    a = solve(AtCoder, s, Contest)
    print(a)

if __name__ == '__main__':
    main()
