#!/usr/bin/env python3
# from typing import *



# def solve(S: str) -> List[str]:
def solve(S):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    A = solve(S)
    print(*[A[i] for i in range(N)])

if __name__ == '__main__':
    main()
