#!/usr/bin/env python3
# from typing import *


# def solve(N: int, A: int, B: int, S: str) -> int:
def solve(N, A, B, S):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, A, B = map(int, input().split())
    S = input()
    a = solve(N, A, B, S)
    print(a)


if __name__ == '__main__':
    main()
