#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(N: int, M: int, A: List[int], X: List[List[int]]) -> str:
def solve(N, M, A, X):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    M = int(next(tokens))
    A = [None for _ in range(M)]
    X = [[None for _ in range(M)] for _ in range(N)]
    for i in range(M):
        A[i] = int(next(tokens))
    for j in range(N):
        for i in range(M):
            X[j][i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, M, A, X)
    print(a)

if __name__ == '__main__':
    main()
