#!/usr/bin/env python3
# from typing import *



# def solve(N: int, Q: int, A: List[int], T: List[int], L: List[int], R: List[int]) -> Tuple[int, List[int]]:
def solve(N, Q, A, T, L, R):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    Q = int(next(tokens))
    A = [None for _ in range(N)]
    T = [None for _ in range(Q)]
    L = [None for _ in range(Q)]
    R = [None for _ in range(Q)]
    for i in range(N):
        A[i] = int(next(tokens))
    for i in range(Q):
        T[i] = int(next(tokens))
        L[i] = int(next(tokens))
        R[i] = int(next(tokens))
    assert next(tokens, None) is None
    n, a = solve(N, Q, A, T, L, R)
    print(n)
    for i in range(n):
        print(a[i])

if __name__ == '__main__':
    main()
