#!/usr/bin/env python3
# from typing import *



# def solve(N: str, Q: str, op: List[str]) -> Any:
def solve(N, Q, op):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, Q = input().split()
    op = [None for _ in range(Q)]
    for i in range(Q):
        op[i] = input()
    ans = solve(N, Q, op)
    print(ans)  # TODO: edit here

if __name__ == '__main__':
    main()
