#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py' number_of_test_cases_you_want
import random

def generate_random_string(min_length=1, max_length=100):
    # Generate a random length for the string within the specified bounds
    length = random.randint(min_length, max_length)
    
    # Build the string with random 'X' and '.' characters
    result = ''.join(random.choice(['X', '.']) for _ in range(length))
    
    return result


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    random_string = generate_random_string()
    print(random_string)
    N = random.randint(0, 200)  # TODO: edit here
    print(N)

if __name__ == "__main__":
    main()
