#!/usr/bin/env python3
# from typing import *


# def solve(a: str, b: List[str], c: List[List[str]], d: str, e: str) -> Tuple[str, List[str]]:
def solve(a, b, c, d, e):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    a = next(tokens)
    b = [None for _ in range(a)]
    c = [[None for _ in range(b_i)] for _ in range(a)]
    for i in range(a):
        b[i] = next(tokens)
        for j in range(b_i):
            c[i][j] = next(tokens)
    d = next(tokens)
    e = next(tokens)
    assert next(tokens, None) is None
    a, b = solve(a, b, c, d, e)
    print(a)
    for i in range(a):
        print(b[i])


if __name__ == '__main__':
    main()
