#!/usr/bin/env python3
# from typing import *



# def solve(N: int, Q: int, A: List[int], l: List[int], r: List[int]) -> Any:
def solve(N, Q, A, l, r):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    Q = int(next(tokens))
    A = [None for _ in range(N)]
    l = [None for _ in range(Q)]
    r = [None for _ in range(Q)]
    for i in range(N):
        A[i] = int(next(tokens))
    for i in range(Q):
        l[i] = int(next(tokens))
        r[i] = int(next(tokens))
    assert next(tokens, None) is None
    ans = solve(N, Q, A, l, r)
    print(ans)  # TODO: edit here

if __name__ == '__main__':
    main()
