#!/usr/bin/env python3
# from typing import *



# def solve(N: int, A: int, B: int, C: int, X: int) -> int:
def solve(N, A, B, C, X):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, A, B, C, X = map(int, input().split())
    a = solve(N, A, B, C, X)
    print(a)

if __name__ == '__main__':
    main()
