#!/usr/bin/env python3
# from typing import *

MOD = 998244353


# def solve(a: str, b: str, c: str, d: List[str], e: List[str], f: List[List[str]]) -> int:
def solve(a, b, c, d, e, f):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    a = next(tokens)
    b = next(tokens)
    c = next(tokens)
    d = [None for _ in range(b)]
    e = [None for _ in range(b)]
    f = [[None for _ in range(b)] for _ in range(b)]
    for i in range(b):
        d[i] = next(tokens)
        e[i] = next(tokens)
        for j in range(i):
            f[i][j] = next(tokens)
    assert next(tokens, None) is None
    a1 = solve(a, b, c, d, e, f)
    print(a1)


if __name__ == '__main__':
    main()
