#!/usr/bin/env python3
# from typing import *



# def solve(N: int, M: int, S: List[str]) -> Tuple[int, List[str]]:
def solve(N, M, S):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    S = [None for _ in range(N)]
    for i in range(N):
        S[i] = input()
    n, a = solve(N, M, S)
    print(n)
    for i in range(n):
        print(a[i])

if __name__ == '__main__':
    main()
