#!/usr/bin/env python3
# from typing import *

MOD = 998244353

# def solve(K: int, C: List[int]) -> int:
def solve(K, C):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    C = [None for _ in range(26)]
    import sys
    tokens = iter(sys.stdin.read().split())
    K = int(next(tokens))
    for i in range(26):
        C[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(K, C)
    print(a)

if __name__ == '__main__':
    main()
