#!/usr/bin/env python3
# from typing import *



# def solve(M: int) -> Tuple[int, List[int]]:
def solve(M):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    M = int(input())
    N, A = solve(M)
    print(N)
    print(*[A[i] for i in range(N)])

if __name__ == '__main__':
    main()
