#!/usr/bin/env python3
# from typing import *

MOD = 998244353


# def solve(X: int, A: int, D: int, N: int) -> int:
def solve(X, A, D, N):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    X, A, D, N = map(int, input().split())
    a = solve(X, A, D, N)
    print(a)


if __name__ == '__main__':
    main()
