#!/usr/bin/env python3
# from typing import *


# def solve(K: int, X: int) -> Any:
def solve(K, X):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    K, X = map(int, input().split())
    ans = solve(K, X)
    print(ans)  # TODO: edit here


if __name__ == '__main__':
    main()
