#!/usr/bin/env python3
# from typing import *



# def solve(n: int, v: List[int]) -> int:
def solve(n, v):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    n = int(next(tokens))
    v = [None for _ in range(n)]
    for i in range(n):
        v[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(n, v)
    print(a)

if __name__ == '__main__':
    main()
