#!/usr/bin/env python3
# from typing import *



# def solve(a: int, b: int, c: int, d: int, e: int) -> Any:
def solve(a, b, c, d, e):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a, b, c, d, e = map(int, input().split())
    ans = solve(a, b, c, d, e)
    print(ans)  # TODO: edit here

if __name__ == '__main__':
    main()
