#!/usr/bin/env python3
# from typing import *


# def solve(n: int, k: int, a: List[str]) -> List[str]:
def solve(n, k, a):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    n, k = map(int, input().split())
    a = [None for _ in range(n)]
    for i in range(n):
        a[i] = input()
    ans = solve(n, k, a)
    print(*[ans[i] for i in range(n)])


if __name__ == '__main__':
    main()
