#!/usr/bin/env python3
# from typing import *


# def solve(N: int, M: int, A: List[int], B: List[int], K: int, C: List[int]) -> int:
def solve(N, M, A, B, K, C):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    M = int(next(tokens))
    A = [None for _ in range(M)]
    B = [None for _ in range(M)]
    for i in range(M):
        A[i] = int(next(tokens))
        B[i] = int(next(tokens))
    K = int(next(tokens))
    C = [None for _ in range(K)]
    for i in range(K):
        C[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, M, A, B, K, C)
    print(a)


if __name__ == '__main__':
    main()
