#!/usr/bin/env python3
# from typing import *



# def solve(N: int, T: int, L: int, u: List[int], v: List[int]) -> List[str]:
def solve(N, T, L, u, v):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, T, L = map(int, input().split())
    u = [None for _ in range(T)]
    v = [None for _ in range(T)]
    for i in range(T):
        u[i], v[i] = map(int, input().split())
    X = solve(N, T, L, u, v)
    print(*[X[i] for i in range(N)])

if __name__ == '__main__':
    main()
