#!/usr/bin/env python3
# from typing import *



# def solve(N: int, C: List[int], A: List[int], B: List[int]) -> Any:
def solve(N, C, A, B):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    C = [None for _ in range(N)]
    A = [None for _ in range(N - 1)]
    B = [None for _ in range(N - 1)]
    for i in range(N):
        C[i] = int(next(tokens))
    for i in range(N - 1):
        A[i] = int(next(tokens))
        B[i] = int(next(tokens))
    assert next(tokens, None) is None
    ans = solve(N, C, A, B)
    print(ans)  # TODO: edit here

if __name__ == '__main__':
    main()
