#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(T: str) -> Tuple[str, str, str]:
def solve(T):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    T = input()
    a, b, c = solve(T)
    print(a)
    print(b)
    print(c)


if __name__ == '__main__':
    main()
