#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py' number_of_test_cases_you_want
import random


def generate_large_number():
    # Decide on the length of the number (between 1 and 200000 digits)
    length = random.randint(1, 200000)
    
    # Generate a random number of the specified length
    # Ensure the first digit is not zero
    number = random.randint(1, 9)
    
    for _ in range(1, length):
        digit = random.randint(0, 9)
        number = number * 10 + digit
    
    return number

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    large_number = generate_large_number()
    print(large_number)

if __name__ == "__main__":
    main()
