#!/usr/bin/env python3
# from typing import *


# def solve(n: int, k: str, a: List[str]) -> Tuple[str, List[str]]:
def solve(n, k, a):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    n = int(next(tokens))
    k = next(tokens)
    a = [None for _ in range(n)]
    for i in range(n):
        a[i] = next(tokens)
    assert next(tokens, None) is None
    K, i = solve(n, k, a)
    print(K)
    print(*[i[j] for j in range(K)])


if __name__ == '__main__':
    main()
