#!/usr/bin/env python3
# from typing import *

YES = 'YES'
NO = 'NO'


# def solve(A: str, B: str, C: str) -> str:
def solve(A, B, C):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A, B, C = input().split()
    a = solve(A, B, C)
    print(a)


if __name__ == '__main__':
    main()
