#!/usr/bin/env python3
# from typing import *

MOD = 1000000007


# def solve(H: int, W: int, N: int, r: List[int], c: List[int]) -> int:
def solve(H, W, N, r, c):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    H, W, N = map(int, input().split())
    r = [None for _ in range(N)]
    c = [None for _ in range(N)]
    for i in range(N):
        r[i], c[i] = map(int, input().split())
    a = solve(H, W, N, r, c)
    print(a)


if __name__ == '__main__':
    main()
