#!/usr/bin/env python3
# from typing import *



# def solve(N: int, M: int, a: List[int], b: List[int], c: List[int]) -> Tuple[int, int, List[int]]:
def solve(N, M, a, b, c):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    M = int(next(tokens))
    a = [None for _ in range(M)]
    b = [None for _ in range(M)]
    c = [None for _ in range(N)]
    for i in range(M):
        a[i] = int(next(tokens))
        b[i] = int(next(tokens))
    for i in range(N):
        c[i] = int(next(tokens))
    assert next(tokens, None) is None
    C, k, p = solve(N, M, a, b, c)
    print(C)
    print(k)
    print(*[p[i] for i in range(k)])

if __name__ == '__main__':
    main()
