#!/usr/bin/env python3
# from typing import *



# def solve(N: int, x: List[int]) -> Tuple[int, float, int]:
def solve(N, x):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    x = [None for _ in range(N)]
    for i in range(N):
        x[i] = int(next(tokens))
    assert next(tokens, None) is None
    d, e, f = solve(N, x)
    print(d)
    print(e)
    print(f)

if __name__ == '__main__':
    main()
