#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py' number_of_test_cases_you_want
import random

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 10)  # TODO: edit here
    K = random.randint(1,N-1)
    print(N, end=" ")
    print(K)
    y = random.randint(1,N)
    A = list(range(K))
    for i in range(K):
        while(y in A):
            y=random.randint(1,N)
        A[i]=y
    A.sort()
    for x in A:
        print(x, end=" ")

if __name__ == "__main__":
    main()
