#!/usr/bin/env python3
# from typing import *


# def solve(N: int, M: int, Q: int, a: List[int], b: List[int], c: List[int], d: List[int]) -> int:
def solve(N, M, Q, a, b, c, d):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M, Q = map(int, input().split())
    a = [None for _ in range(Q)]
    b = [None for _ in range(Q)]
    c = [None for _ in range(Q)]
    d = [None for _ in range(Q)]
    for i in range(Q):
        a[i], b[i], c[i], d[i] = map(int, input().split())
    a1 = solve(N, M, Q, a, b, c, d)
    print(a1)


if __name__ == '__main__':
    main()
