#!/usr/bin/env python3
# from typing import *


# def solve(N: int, x: List[int], y: List[int], Q: int, a: List[int], b: List[int], K: List[int]) -> Tuple[List[str], str, str]:
def solve(N, x, y, Q, a, b, K):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    x = [None for _ in range(N)]
    y = [None for _ in range(N)]
    for i in range(N):
        x[i], y[i] = map(int, input().split())
    Q = int(input())
    a = [None for _ in range(Q)]
    b = [None for _ in range(Q)]
    K = [None for _ in range(Q)]
    for i in range(Q):
        a[i], b[i], K[i] = map(int, input().split())
    f, g, h = solve(N, x, y, Q, a, b, K)
    for i in range(N):
        print(f[i])
    print(g)
    print(h)


if __name__ == '__main__':
    main()
