#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py' number_of_test_cases_you_want
import random
import string
# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 20)  # TODO: edit here
    A = [None for _ in range(N)]
    letters = string.ascii_lowercase
    print(N)
    print(''.join(random.choice(letters) for i in range(N)))

if __name__ == "__main__":
    main()
