#!/usr/bin/env python3
# from typing import *



# def solve(N: int, Q: int, X: List[int], A: List[int], B: List[int], V: List[int], K: List[int]) -> List[str]:
def solve(N, Q, X, A, B, V, K):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    Q = int(next(tokens))
    X = [None for _ in range(N)]
    A = [None for _ in range(N - 1)]
    B = [None for _ in range(N - 1)]
    V = [None for _ in range(Q)]
    K = [None for _ in range(Q)]
    for i in range(N):
        X[i] = int(next(tokens))
    for i in range(N - 1):
        A[i] = int(next(tokens))
        B[i] = int(next(tokens))
    for i in range(Q):
        V[i] = int(next(tokens))
        K[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, Q, X, A, B, V, K)
    for i in range(Q):
        print(a[i])

if __name__ == '__main__':
    main()
