#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py' number_of_test_cases_you_want
import random

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(2, 100000)  # TODO: edit here
    M = random.randint(1, N-1)  # TODO: edit here
    print(N, end=" ")
    print(M)
    Aset=set()
    Bset=set()
    for _ in range(M):
        A = random.randint(1, N)  # TODO: edit here
        while(A in Aset):
            A = random.randint(1, N)  # TODO: edit here
        B = random.randint(1, N)  # TODO: edit here
        while(B in Bset):
            B = random.randint(1,N)
        Aset.add(A)
        Bset.add(B)
        print(A, end=" ")
        print(B)

if __name__ == "__main__":
    main()
