#!/usr/bin/env python3
# from typing import *

NO = 'No'

# def solve(N: int, M: int, X: int, Y: int, x: List[int], y: List[int]) -> Any:
def solve(N, M, X, Y, x, y):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    M = int(next(tokens))
    X = int(next(tokens))
    Y = int(next(tokens))
    x = [None for _ in range(N)]
    y = [None for _ in range(M)]
    for i in range(N):
        x[i] = int(next(tokens))
    for i in range(M):
        y[i] = int(next(tokens))
    assert next(tokens, None) is None
    ans = solve(N, M, X, Y, x, y)
    print(ans)  # TODO: edit here

if __name__ == '__main__':
    main()
