#!/usr/bin/env python3
# from typing import *

MOD = 1000000007


# def solve(n: int, a: List[int]) -> Tuple[str, List[str]]:
def solve(n, a):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    n = int(next(tokens))
    a = [None for _ in range(n + 1)]
    for i in range(n + 1):
        a[i] = int(next(tokens))
    assert next(tokens, None) is None
    n1, a1 = solve(n, a)
    print(n1)
    for i in range(n1):
        print(a1[i])


if __name__ == '__main__':
    main()
