#!/usr/bin/env python3
# from typing import *



# def solve(N: int, D: int, x: List[int], y: List[int]) -> int:
def solve(N, D, x, y):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, D = map(int, input().split())
    x = [None for _ in range(N)]
    y = [None for _ in range(N)]
    for i in range(N):
        x[i], y[i] = map(int, input().split())
    a = solve(N, D, x, y)
    print(a)

if __name__ == '__main__':
    main()
