#!/usr/bin/env python3
# from typing import *



# def solve(T: int, N: List[int], M: List[int], A: List[int], B: List[int]) -> List[str]:
def solve(T, N, M, A, B):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    T = int(input())
    N = [None for _ in range(T)]
    M = [None for _ in range(T)]
    A = [None for _ in range(T)]
    B = [None for _ in range(T)]
    for i in range(T):
        N[i], M[i], A[i], B[i] = map(int, input().split())
    ans = solve(T, N, M, A, B)
    for i in range(T):
        print(ans[i])

if __name__ == '__main__':
    main()
