#!/usr/bin/env python3
# from typing import *



# def solve(R: str, C: str, B: List[List[str]]) -> Any:
def solve(R, C, B):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    R = next(tokens)
    C = next(tokens)
    B = [[None for _ in range(C)] for _ in range(C + R + 2)]
    for j in range(R + 2):
        for i in range(C):
            B[i + j][i] = next(tokens)
    assert next(tokens, None) is None
    ans = solve(R, C, B)
    print(ans)  # TODO: edit here

if __name__ == '__main__':
    main()
