#!/usr/bin/env python3
# from typing import *

MOD = 998244353

# def solve(N: str, M: str, K: str, X: List[str], Y: List[str]) -> int:
def solve(N, M, K, X, Y):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M, K = input().split()
    X = [None for _ in range(M)]
    Y = [None for _ in range(M)]
    for i in range(M):
        X[i], Y[i] = input().split()
    a = solve(N, M, K, X, Y)
    print(a)

if __name__ == '__main__':
    main()
