#!/usr/bin/env python3
# from typing import *



# def solve(N: int, M: int, U: List[int], V: List[int], W: List[int], Q: int, A: List[int], S: List[int], T: List[int]) -> List[str]:
def solve(N, M, U, V, W, Q, A, S, T):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    U = [None for _ in range(M)]
    V = [None for _ in range(M)]
    W = [None for _ in range(M)]
    for i in range(M):
        U[i], V[i], W[i] = map(int, input().split())
    Q = int(input())
    A = [None for _ in range(Q)]
    S = [None for _ in range(Q)]
    T = [None for _ in range(Q)]
    for i in range(Q):
        A[i], S[i], T[i] = map(int, input().split())
    a = solve(N, M, U, V, W, Q, A, S, T)
    for i in range(Q):
        print(a[i])

if __name__ == '__main__':
    main()
