#!/usr/bin/env python3
# from typing import *



# def solve(t: int, N: int) -> int:
def solve(t, N):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    t, N = map(int, input().split())
    a = solve(t, N)
    print(a)

if __name__ == '__main__':
    main()
