#!/usr/bin/env python3
# from typing import *


# def solve(N: str, M: str, L: str, A: List[str], B: List[str], C: List[str], Q: str, s: List[str], t: List[str]) -> Any:
def solve(N, M, L, A, B, C, Q, s, t):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M, L = input().split()
    A = [None for _ in range(M)]
    B = [None for _ in range(M)]
    C = [None for _ in range(M)]
    for i in range(M):
        A[i], B[i], C[i] = input().split()
    Q = input()
    s = [None for _ in range(Q)]
    t = [None for _ in range(Q)]
    for i in range(Q):
        s[i], t[i] = input().split()
    ans = solve(N, M, L, A, B, C, Q, s, t)
    print(ans)  # TODO: edit here


if __name__ == '__main__':
    main()
