#!/usr/bin/env python3
# from typing import *

MOD = 998244353

# def solve(N: str, M: str, K: str, u: List[str], v: List[str]) -> int:
def solve(N, M, K, u, v):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M, K = input().split()
    u = [None for _ in range(M)]
    v = [None for _ in range(M)]
    for i in range(M):
        u[i], v[i] = input().split()
    a = solve(N, M, K, u, v)
    print(a)

if __name__ == '__main__':
    main()
