#!/usr/bin/env python3
# from typing import *


# def solve(a: List[int]) -> int:
def solve(a):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = [None for _ in range(10)]
    import sys
    tokens = iter(sys.stdin.read().split())
    for i in range(10):
        a[i] = int(next(tokens))
    assert next(tokens, None) is None
    a1 = solve(a)
    print(a1)


if __name__ == '__main__':
    main()
