#!/usr/bin/env python3
# from typing import *


# def solve(H: int, W: int, T: int, s: List[List[int]]) -> int:
def solve(H, W, T, s):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    H = int(next(tokens))
    W = int(next(tokens))
    T = int(next(tokens))
    s = [[None for _ in range(W)] for _ in range(H)]
    for j in range(H):
        for i in range(W):
            s[j][i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(H, W, T, s)
    print(a)


if __name__ == '__main__':
    main()
