#!/usr/bin/env python3
# from typing import *



# def solve(K: int, N: int, M: int, A: List[int]) -> List[str]:
def solve(K, N, M, A):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    K = int(next(tokens))
    N = int(next(tokens))
    M = int(next(tokens))
    A = [None for _ in range(K)]
    for i in range(K):
        A[i] = int(next(tokens))
    assert next(tokens, None) is None
    B = solve(K, N, M, A)
    print(*[B[i] for i in range(K)])

if __name__ == '__main__':
    main()
