#!/usr/bin/env python3
# from typing import *



# def solve(N: int, q: List[int], r: List[int], Q: int, t: List[int], d: List[int]) -> Tuple[List[str], str, str]:
def solve(N, q, r, Q, t, d):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    q = [None for _ in range(N)]
    r = [None for _ in range(N)]
    for i in range(N):
        q[i], r[i] = map(int, input().split())
    Q = int(input())
    t = [None for _ in range(Q)]
    d = [None for _ in range(Q)]
    for i in range(Q):
        t[i], d[i] = map(int, input().split())
    e, f, g = solve(N, q, r, Q, t, d)
    for i in range(N):
        print(e[i])
    print(f)
    print(g)

if __name__ == '__main__':
    main()
