#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(N: int, M: int, A: int, B: int, L: List[int], R: List[int]) -> str:
def solve(N, M, A, B, L, R):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M, A, B = map(int, input().split())
    L = [None for _ in range(M)]
    R = [None for _ in range(M)]
    for i in range(M):
        L[i], R[i] = map(int, input().split())
    a = solve(N, M, A, B, L, R)
    print(a)

if __name__ == '__main__':
    main()
