#!/usr/bin/env python3
# from typing import *



# def solve(N: int, S: int, K: int, P: List[int], Q: List[int]) -> int:
def solve(N, S, K, P, Q):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, S, K = map(int, input().split())
    P = [None for _ in range(N)]
    Q = [None for _ in range(N)]
    for i in range(N):
        P[i], Q[i] = map(int, input().split())
    a = solve(N, S, K, P, Q)
    print(a)

if __name__ == '__main__':
    main()
