#!/usr/bin/env python3
# from typing import *



# def solve(N: int, K: int, M: int) -> List[str]:
def solve(N, K, M):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, K, M = map(int, input().split())
    c = solve(N, K, M)
    for i in range(N):
        print(c[i])

if __name__ == '__main__':
    main()
