#!/usr/bin/env python3
# from typing import *


# def solve(N: int, X: int, Y: int, P: List[int], T: List[int], Q: int, q: List[int]) -> List[str]:
def solve(N, X, Y, P, T, Q, q):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, X, Y = map(int, input().split())
    P = [None for _ in range(N - 1)]
    T = [None for _ in range(N - 1)]
    for i in range(N - 1):
        P[i], T[i] = map(int, input().split())
    Q = int(input())
    q = [None for _ in range(Q)]
    for i in range(Q):
        q[i] = int(input())
    a = solve(N, X, Y, P, T, Q, q)
    for i in range(Q):
        print(a[i])


if __name__ == '__main__':
    main()
