#!/usr/bin/env python3
# from typing import *

YES = 'YES'
NO = 'NO'


# def solve(r: int, g: int, b: int) -> str:
def solve(r, g, b):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    r, g, b = map(int, input().split())
    a = solve(r, g, b)
    print(a)


if __name__ == '__main__':
    main()
