#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(N: int, W: int, S: List[int], T: List[int], P: List[int]) -> str:
def solve(N, W, S, T, P):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, W = map(int, input().split())
    S = [None for _ in range(N)]
    T = [None for _ in range(N)]
    P = [None for _ in range(N)]
    for i in range(N):
        S[i], T[i], P[i] = map(int, input().split())
    a = solve(N, W, S, T, P)
    print(a)


if __name__ == '__main__':
    main()
