#!/usr/bin/env python3
# from typing import *



# def solve(S: str, T: str) -> Tuple[str, str]:
def solve(S, T):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S, T = input().split()
    c, d = solve(S, T)
    print(c, d)

if __name__ == '__main__':
    main()
