#!/usr/bin/env python3
# from typing import *



# def solve(S: List[str]) -> int:
def solve(S):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = [None for _ in range(12)]
    for i in range(12):
        S[i] = input()
    a = solve(S)
    print(a)

if __name__ == '__main__':
    main()
