#!/usr/bin/env python3
# from typing import *



# def solve(N: int, S: str, Q: int, T: List[int], A: List[int], B: List[int]) -> str:
def solve(N, S, Q, T, A, B):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    S = input()
    Q = int(input())
    T = [None for _ in range(Q)]
    A = [None for _ in range(Q)]
    B = [None for _ in range(Q)]
    for i in range(Q):
        T[i], A[i], B[i] = map(int, input().split())
    a = solve(N, S, Q, T, A, B)
    print(a)

if __name__ == '__main__':
    main()
