#!/usr/bin/env python3
# from typing import *


# def solve(N: int, w: List[int], s: List[int], v: List[int]) -> int:
def solve(N, w, s, v):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    w = [None for _ in range(N)]
    s = [None for _ in range(N)]
    v = [None for _ in range(N)]
    for i in range(N):
        w[i], s[i], v[i] = map(int, input().split())
    a = solve(N, w, s, v)
    print(a)


if __name__ == '__main__':
    main()
