#!/usr/bin/env python3
# from typing import *



# def solve(M: int, D: int, y: int, m: int, d: int) -> Tuple[int, int, int]:
def solve(M, D, y, m, d):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    M, D = map(int, input().split())
    y, m, d = map(int, input().split())
    e, f, g = solve(M, D, y, m, d)
    print(e, f, g)

if __name__ == '__main__':
    main()
