#!/usr/bin/env python3
# from typing import *



# def solve(N: int, A: List[int], C: List[int]) -> Tuple[int, List[int]]:
def solve(N, A, C):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    A = [None for _ in range(N)]
    C = [None for _ in range(N)]
    for i in range(N):
        A[i], C[i] = map(int, input().split())
    m, i = solve(N, A, C)
    print(m)
    print(*[i[j] for j in range(m)])

if __name__ == '__main__':
    main()
