#!/usr/bin/env python3
# from typing import *



# def solve(N: str, H: str, X: List[str], P: List[str], F: List[str]) -> int:
def solve(N, H, X, P, F):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = next(tokens)
    H = next(tokens)
    X = [None for _ in range(N)]
    P = [None for _ in range(N - 1)]
    F = [None for _ in range(N - 1)]
    for i in range(N):
        X[i] = next(tokens)
    for i in range(N - 1):
        P[i] = next(tokens)
        F[i] = next(tokens)
    assert next(tokens, None) is None
    a = solve(N, H, X, P, F)
    print(a)

if __name__ == '__main__':
    main()
