#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(W: int, B: int) -> str:
def solve(W, B):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    W, B = map(int, input().split())
    a = solve(W, B)
    print(a)


if __name__ == '__main__':
    main()
