#!/usr/bin/env python3
# from typing import *


# def solve(M: int, K: int) -> Any:
def solve(M, K):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    M, K = map(int, input().split())
    ans = solve(M, K)
    print(ans)  # TODO: edit here


if __name__ == '__main__':
    main()
