#!/usr/bin/env python3
# from typing import *



# def solve(Q: int, t: List[int], x: List[int]) -> Tuple[int, int]:
def solve(Q, t, x):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    Q = int(input())
    t = [None for _ in range(Q)]
    x = [None for _ in range(Q)]
    for i in range(Q):
        t[i], x[i] = map(int, input().split())
    c, d = solve(Q, t, x)
    print(c)
    print(d)

if __name__ == '__main__':
    main()
