#!/usr/bin/env python3
# from typing import *

MOD = 1000000007

# def solve(N: str, K: int) -> int:
def solve(N, K):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = next(tokens)
    K = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, K)
    print(a)

if __name__ == '__main__':
    main()
