#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(N: int, Q: int, l: List[int], r: List[int]) -> str:
def solve(N, Q, l, r):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, Q = map(int, input().split())
    l = [None for _ in range(Q)]
    r = [None for _ in range(Q)]
    for i in range(Q):
        l[i], r[i] = map(int, input().split())
    a = solve(N, Q, l, r)
    print(a)


if __name__ == '__main__':
    main()
