#!/usr/bin/env python3
# from typing import *


# def solve(N: int, P: List[List[int]], R: List[List[int]], D: List[List[int]]) -> int:
def solve(N, P, R, D):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    P = [[None for _ in range(N)] for _ in range(N)]
    R = [[None for _ in range(N - 1)] for _ in range(N)]
    D = [[None for _ in range(N)] for _ in range(N - 1)]
    for j in range(N):
        for i in range(N):
            P[j][i] = int(next(tokens))
    for j in range(N):
        for i in range(N - 1):
            R[j][i] = int(next(tokens))
    for j in range(N - 1):
        for i in range(N):
            D[j][i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, P, R, D)
    print(a)


if __name__ == '__main__':
    main()
