#!/usr/bin/env python3
# from typing import *


# def solve(L: int, R: int, S: str) -> str:
def solve(L, R, S):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    L, R = map(int, input().split())
    S = input()
    a = solve(L, R, S)
    print(a)


if __name__ == '__main__':
    main()
