#!/usr/bin/env python3
# from typing import *


# def solve(H: int, W: int, R: int, C: int) -> int:
def solve(H, W, R, C):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    H, W = map(int, input().split())
    R, C = map(int, input().split())
    a = solve(H, W, R, C)
    print(a)


if __name__ == '__main__':
    main()
