#!/usr/bin/env python3
# from typing import *



# def solve(B: int, G: int) -> str:
def solve(B, G):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    B, G = map(int, input().split())
    a = solve(B, G)
    print(a)

if __name__ == '__main__':
    main()
