#!/usr/bin/env python3
# from typing import *



# def solve(N: int, P: List[int], Q: int, U: List[int], D: List[int]) -> Tuple[int, List[int]]:
def solve(N, P, Q, U, D):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    P = [None for _ in range(N - 1)]
    for i in range(N - 1):
        P[i] = int(next(tokens))
    Q = int(next(tokens))
    U = [None for _ in range(Q)]
    D = [None for _ in range(Q)]
    for i in range(Q):
        U[i] = int(next(tokens))
        D[i] = int(next(tokens))
    assert next(tokens, None) is None
    n, a = solve(N, P, Q, U, D)
    print(n)
    for i in range(n):
        print(a[i])

if __name__ == '__main__':
    main()
