#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(N: int, W: List[str]) -> str:
def solve(N, W):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    W = [None for _ in range(N)]
    for i in range(N):
        W[i] = next(tokens)
    assert next(tokens, None) is None
    a = solve(N, W)
    print(a)

if __name__ == '__main__':
    main()
