#!/usr/bin/env python3
# from typing import *


# def solve(N: int, A: int, B: int, h: List[int]) -> int:
def solve(N, A, B, h):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, A, B = map(int, input().split())
    h = [None for _ in range(N)]
    for i in range(N):
        h[i] = int(input())
    a = solve(N, A, B, h)
    print(a)


if __name__ == '__main__':
    main()
