#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(N: int, M: int, A: List[str], B: List[str]) -> str:
def solve(N, M, A, B):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    A = [None for _ in range(N)]
    B = [None for _ in range(M)]
    for i in range(N):
        A[i] = input()
    for i in range(M):
        B[i] = input()
    a = solve(N, M, A, B)
    print(a)

if __name__ == '__main__':
    main()
