#!/usr/bin/env python3
# from typing import *

MOD = 998244353

# def solve(N: int, Q: int, L: List[int], R: List[int], C: List[int]) -> int:
def solve(N, Q, L, R, C):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, Q = map(int, input().split())
    L = [None for _ in range(Q)]
    R = [None for _ in range(Q)]
    C = [None for _ in range(Q)]
    for i in range(Q):
        L[i], R[i], C[i] = map(int, input().split())
    a = solve(N, Q, L, R, C)
    print(a)

if __name__ == '__main__':
    main()
