#!/usr/bin/env python3
# from typing import *



# def solve(N: int, X: List[int], P: List[int], Q: int, L: List[int], R: List[int]) -> List[str]:
def solve(N, X, P, Q, L, R):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    X = [None for _ in range(N)]
    P = [None for _ in range(N)]
    for i in range(N):
        X[i] = int(next(tokens))
    for i in range(N):
        P[i] = int(next(tokens))
    Q = int(next(tokens))
    L = [None for _ in range(Q)]
    R = [None for _ in range(Q)]
    for i in range(Q):
        L[i] = int(next(tokens))
        R[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, X, P, Q, L, R)
    for i in range(Q):
        print(a[i])

if __name__ == '__main__':
    main()
