#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(X: int, Y: int, A: int, B: int, C: int) -> str:
def solve(X, Y, A, B, C):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    X, Y, A, B, C = map(int, input().split())
    a = solve(X, Y, A, B, C)
    print(a)

if __name__ == '__main__':
    main()
