#!/usr/bin/env python3
# from typing import *


# def solve(N: int, M: int, T: List[int], X: List[int]) -> int:
def solve(N, M, T, X):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    T = [None for _ in range(N)]
    X = [None for _ in range(N)]
    for i in range(N):
        T[i], X[i] = map(int, input().split())
    a = solve(N, M, T, X)
    print(a)


if __name__ == '__main__':
    main()
