#!/usr/bin/env python3
# from typing import *


# def solve(A: List[str]) -> Any:
def solve(A):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A = [None for _ in range(N)]
    for i in range(N):
        A[i] = input()
    ans = solve(A)
    print(ans)  # TODO: edit here


if __name__ == '__main__':
    main()
