#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(N: int, p: List[int], t: List[int], s: List[int], g: List[int]) -> str:
def solve(N, p, t, s, g):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    p = [None for _ in range(N - 1)]
    t = [None for _ in range(N - 1)]
    s = [None for _ in range(N - 1)]
    g = [None for _ in range(N - 1)]
    for i in range(N - 1):
        p[i], t[i], s[i], g[i] = map(int, input().split())
    a = solve(N, p, t, s, g)
    print(a)


if __name__ == '__main__':
    main()
