#!/usr/bin/env python3
# from typing import *



# def solve(A: int, B: int, D: int) -> Any:
def solve(A, B, D):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A, B, D = map(int, input().split())
    ans = solve(A, B, D)
    print(ans)  # TODO: edit here

if __name__ == '__main__':
    main()
