#!/usr/bin/env python3
# from typing import *



# def solve(N: int, X: int, V: List[int], A: List[int], C: List[int]) -> int:
def solve(N, X, V, A, C):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, X = map(int, input().split())
    V = [None for _ in range(N)]
    A = [None for _ in range(N)]
    C = [None for _ in range(N)]
    for i in range(N):
        V[i], A[i], C[i] = map(int, input().split())
    a = solve(N, X, V, A, C)
    print(a)

if __name__ == '__main__':
    main()
