#!/usr/bin/env python3
# from typing import *



# def solve(A: int) -> int:
def solve(A):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A = int(input())
    a = solve(A)
    print(a)

if __name__ == '__main__':
    main()
