#!/usr/bin/env python3
# from typing import *



# def solve(N: int, X: List[int], Y: List[int], Q: int, A: List[int], B: List[int]) -> List[str]:
def solve(N, X, Y, Q, A, B):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    X = [None for _ in range(N)]
    Y = [None for _ in range(N)]
    for i in range(N):
        X[i], Y[i] = map(int, input().split())
    Q = int(input())
    A = [None for _ in range(Q)]
    B = [None for _ in range(Q)]
    for i in range(Q):
        A[i], B[i] = map(int, input().split())
    a = solve(N, X, Y, Q, A, B)
    for i in range(Q):
        print(a[i])

if __name__ == '__main__':
    main()
