#!/usr/bin/env python3
# from typing import *



# def solve(N: int, A: List[int], B: List[int], Q: int, C: List[int], D: List[int]) -> List[str]:
def solve(N, A, B, Q, C, D):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    A = [None for _ in range(N)]
    B = [None for _ in range(N)]
    for i in range(N):
        A[i], B[i] = map(int, input().split())
    Q = int(input())
    C = [None for _ in range(Q)]
    D = [None for _ in range(Q)]
    for i in range(Q):
        C[i], D[i] = map(int, input().split())
    a = solve(N, A, B, Q, C, D)
    for i in range(Q):
        print(a[i])

if __name__ == '__main__':
    main()
