#!/usr/bin/env python3
# from typing import *

MOD = 998244353


# def solve(N: int, A: List[int]) -> Tuple[List[str], str, List[str], List[str], str]:
def solve(N, A):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    A = [None for _ in range(N)]
    for i in range(N):
        A[i] = int(next(tokens))
    assert next(tokens, None) is None
    f, g, h, m, n = solve(N, A)
    for i in range(N):
        print(f[i])
    print(g)
    for i in range(g):
        print(h[i])
        print(m[i])
    print(n)


if __name__ == '__main__':
    main()
