#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py' number_of_test_cases_you_want
import random

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 3)  # TODO: edit here
    M = random.randint(0,5)
    print(N, end=" ")
    print(M)
    """ print(*[A[i] for i in range(N)]) """
    for i in range(M):
        print(random.randint(1,N), end=" ")
        print(random.randint(0,9))

if __name__ == "__main__":
    main()
