#!/usr/bin/env python3
# from typing import *



# def solve(a: int, b: int, c: List[int], d: List[List[int]], e: List[int], f: List[int]) -> List[str]:
def solve(a, b, c, d, e, f):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    a = int(next(tokens))
    b = int(next(tokens))
    c = [None for _ in range(b)]
    d = [[None for _ in range(c_i)] for _ in range(b)]
    e = [None for _ in range(a)]
    f = [None for _ in range(a)]
    for i in range(b):
        c[i] = int(next(tokens))
        for j in range(c_i):
            d[i][j] = int(next(tokens))
    for i in range(a):
        e[i] = int(next(tokens))
        f[i] = int(next(tokens))
    assert next(tokens, None) is None
    g = solve(a, b, c, d, e, f)
    for i in range(b):
        print(g[i])

if __name__ == '__main__':
    main()
