#!/usr/bin/env python3
# from typing import *



# def solve(N: int, M: int, K: int, A: List[int], B: List[int], C: List[int], D: List[int]) -> float:
def solve(N, M, K, A, B, C, D):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M, K = map(int, input().split())
    A = [None for _ in range(N)]
    B = [None for _ in range(N)]
    C = [None for _ in range(M)]
    D = [None for _ in range(M)]
    for i in range(N):
        A[i], B[i] = map(int, input().split())
    for i in range(M):
        C[i], D[i] = map(int, input().split())
    a = solve(N, M, K, A, B, C, D)
    print(a)

if __name__ == '__main__':
    main()
