#!/usr/bin/env python3
# from typing import *

MOD = 1000000007

# def solve(N: int, M: int, K: int, A: List[int], X: List[int], Y: List[int]) -> List[str]:
def solve(N, M, K, A, X, Y):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    M = int(next(tokens))
    K = int(next(tokens))
    A = [None for _ in range(N)]
    X = [None for _ in range(M)]
    Y = [None for _ in range(M)]
    for i in range(N):
        A[i] = int(next(tokens))
    for i in range(M):
        X[i] = int(next(tokens))
        Y[i] = int(next(tokens))
    assert next(tokens, None) is None
    ans = solve(N, M, K, A, X, Y)
    for i in range(N):
        print(ans[i])

if __name__ == '__main__':
    main()
