#!/usr/bin/env python3
# from typing import *


# def solve(N: int, S: str, Q: int, t: List[int], x: List[int], c: List[str]) -> str:
def solve(N, S, Q, t, x, c):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    S = next(tokens)
    Q = int(next(tokens))
    t = [None for _ in range(Q)]
    x = [None for _ in range(Q)]
    c = [None for _ in range(Q)]
    for i in range(Q):
        t[i] = int(next(tokens))
        x[i] = int(next(tokens))
        c[i] = next(tokens)
    assert next(tokens, None) is None
    a = solve(N, S, Q, t, x, c)
    print(a)


if __name__ == '__main__':
    main()
