#!/usr/bin/env python3
# from typing import *



# def solve(K: int, G: int, M: int) -> Tuple[int, int]:
def solve(K, G, M):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    K, G, M = map(int, input().split())
    c, d = solve(K, G, M)
    print(c, d)

if __name__ == '__main__':
    main()
