#!/usr/bin/env python3
# from typing import *



# def solve(M: int) -> int:
def solve(M):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    M = int(input())
    a = solve(M)
    print(a)

if __name__ == '__main__':
    main()
