#!/usr/bin/env python3
# from typing import *



# def solve(X: int, t: int) -> int:
def solve(X, t):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    X, t = map(int, input().split())
    a = solve(X, t)
    print(a)

if __name__ == '__main__':
    main()
