#!/usr/bin/env python3
# from typing import *



# def solve(N: int, D: int, S: str) -> str:
def solve(N, D, S):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, D = map(int, input().split())
    S = input()
    a = solve(N, D, S)
    print(a)

if __name__ == '__main__':
    main()
