#!/usr/bin/env python3
# from typing import *



# def solve(a: int, b: int, h: int) -> int:
def solve(a, b, h):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = int(input())
    b = int(input())
    h = int(input())
    a1 = solve(a, b, h)
    print(a1)

if __name__ == '__main__':
    main()
