#!/usr/bin/env python3
# from typing import *



# def solve(N: int, x: List[int], y: List[int], h: List[int]) -> Tuple[int, int, int]:
def solve(N, x, y, h):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    x = [None for _ in range(N)]
    y = [None for _ in range(N)]
    h = [None for _ in range(N)]
    for i in range(N):
        x[i], y[i], h[i] = map(int, input().split())
    d, e, f = solve(N, x, y, h)
    print(d, e, f)

if __name__ == '__main__':
    main()
