#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(a: int, b: int, c: List[str]) -> str:
def solve(a, b, c):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a, b = map(int, input().split())
    c = [None for _ in range(b)]
    for i in range(b):
        c[i] = input()
    a1 = solve(a, b, c)
    print(a1)

if __name__ == '__main__':
    main()
