#!/usr/bin/env python3
# from typing import *



# def solve(N: int, Q: int, t: List[int], u: List[int], v: List[int]) -> List[str]:
def solve(N, Q, t, u, v):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, Q = map(int, input().split())
    t = [None for _ in range(Q)]
    u = [None for _ in range(Q)]
    v = [None for _ in range(Q)]
    for i in range(Q):
        t[i], u[i], v[i] = map(int, input().split())
    ans = solve(N, Q, t, u, v)
    for i in range(N):
        print(ans[i])

if __name__ == '__main__':
    main()
