#!/usr/bin/env python3
# from typing import *

MOD = 998244353

# def solve(N: int, M: int, A: List[int], L: List[int], R: List[int], X: List[int]) -> List[str]:
def solve(N, M, A, L, R, X):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    M = int(next(tokens))
    A = [None for _ in range(N)]
    L = [None for _ in range(M)]
    R = [None for _ in range(M)]
    X = [None for _ in range(M)]
    for i in range(N):
        A[i] = int(next(tokens))
    for i in range(M):
        L[i] = int(next(tokens))
        R[i] = int(next(tokens))
        X[i] = int(next(tokens))
    assert next(tokens, None) is None
    E = solve(N, M, A, L, R, X)
    print(*[E[i] for i in range(N)])

if __name__ == '__main__':
    main()
