#!/usr/bin/env python3
# from typing import *



# def solve(Q: str, query: List[str]) -> Any:
def solve(Q, query):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    Q = input()
    query = [None for _ in range(Q)]
    for i in range(Q):
        query[i] = input()
    ans = solve(Q, query)
    print(ans)  # TODO: edit here

if __name__ == '__main__':
    main()
