#!/usr/bin/env python3
# from typing import *



# def solve(N: int, M: int, C: int, A: List[int], u: List[int], v: List[int], c: List[int]) -> int:
def solve(N, M, C, A, u, v, c):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    M = int(next(tokens))
    C = int(next(tokens))
    A = [None for _ in range(C)]
    u = [None for _ in range(M)]
    v = [None for _ in range(M)]
    c = [None for _ in range(M)]
    for i in range(C):
        A[i] = int(next(tokens))
    for i in range(M):
        u[i] = int(next(tokens))
        v[i] = int(next(tokens))
        c[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, M, C, A, u, v, c)
    print(a)

if __name__ == '__main__':
    main()
