#!/usr/bin/env python3
# from typing import *



# def solve(N: int, W: List[int], X: List[int]) -> int:
def solve(N, W, X):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    W = [None for _ in range(N)]
    X = [None for _ in range(N)]
    for i in range(N):
        W[i], X[i] = map(int, input().split())
    a = solve(N, W, X)
    print(a)

if __name__ == '__main__':
    main()
