#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(N: int, M: int, S: List[str], T: List[str]) -> List[str]:
def solve(N, M, S, T):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    M = int(next(tokens))
    S = [None for _ in range(N)]
    T = [None for _ in range(M)]
    for i in range(N):
        S[i] = next(tokens)
    for i in range(M):
        T[i] = next(tokens)
    assert next(tokens, None) is None
    ans = solve(N, M, S, T)
    for i in range(N):
        print(ans[i])

if __name__ == '__main__':
    main()
