#!/usr/bin/env python3
# from typing import *


# def solve(p: str, q: str) -> int:
def solve(p, q):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    p, q = input().split()
    a = solve(p, q)
    print(a)


if __name__ == '__main__':
    main()
