#!/usr/bin/env python3
# from typing import *



# def solve(R: int, X: int, Y: int) -> int:
def solve(R, X, Y):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    R, X, Y = map(int, input().split())
    a = solve(R, X, Y)
    print(a)

if __name__ == '__main__':
    main()
