#!/usr/bin/env python3
# from typing import *



# def solve(N: int, C: int, M: int, T: List[int], P: List[int]) -> int:
def solve(N, C, M, T, P):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, C = map(int, input().split())
    M = int(input())
    T = [None for _ in range(M)]
    P = [None for _ in range(M)]
    for i in range(M):
        T[i], P[i] = map(int, input().split())
    a = solve(N, C, M, T, P)
    print(a)

if __name__ == '__main__':
    main()
