#!/usr/bin/env python3
# from typing import *



# def solve(N: int, T: int, C: List[int], R: List[int]) -> int:
def solve(N, T, C, R):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    T = int(next(tokens))
    C = [None for _ in range(N)]
    R = [None for _ in range(N)]
    for i in range(N):
        C[i] = int(next(tokens))
    for i in range(N):
        R[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, T, C, R)
    print(a)

if __name__ == '__main__':
    main()
