#!/usr/bin/env python3
# from typing import *



# def solve(R: int, C: int, K: int, r: List[int], c: List[int], v: List[int]) -> int:
def solve(R, C, K, r, c, v):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    R, C, K = map(int, input().split())
    r = [None for _ in range(K)]
    c = [None for _ in range(K)]
    v = [None for _ in range(K)]
    for i in range(K):
        r[i], c[i], v[i] = map(int, input().split())
    a = solve(R, C, K, r, c, v)
    print(a)

if __name__ == '__main__':
    main()
