#!/usr/bin/env python3
# from typing import *



# def solve(R: int, G: int) -> int:
def solve(R, G):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    R = int(input())
    G = int(input())
    a = solve(R, G)
    print(a)

if __name__ == '__main__':
    main()
