#!/usr/bin/env python3
# from typing import *



# def solve(N: int, M: int, S: str) -> int:
def solve(N, M, S):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    S = input()
    b = solve(N, M, S)
    print(b)

if __name__ == '__main__':
    main()
