#!/usr/bin/env python3
# from typing import *

NO = 'Impossible'


# def solve(N: int, A: List[int], S: List[str], Q: int, U: List[int], V: List[int]) -> Any:
def solve(N, A, S, Q, U, V):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    A = [None for _ in range(N)]
    S = [None for _ in range(N)]
    for i in range(N):
        A[i] = int(next(tokens))
    for i in range(N):
        S[i] = next(tokens)
    Q = int(next(tokens))
    U = [None for _ in range(Q)]
    V = [None for _ in range(Q)]
    for i in range(Q):
        U[i] = int(next(tokens))
        V[i] = int(next(tokens))
    assert next(tokens, None) is None
    ans = solve(N, A, S, Q, U, V)
    print(ans)  # TODO: edit here


if __name__ == '__main__':
    main()
