#!/usr/bin/env python3
# from typing import *



# def solve(N: int, D: int, T: List[int], L: List[int]) -> List[str]:
def solve(N, D, T, L):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, D = map(int, input().split())
    T = [None for _ in range(N)]
    L = [None for _ in range(N)]
    for i in range(N):
        T[i], L[i] = map(int, input().split())
    a = solve(N, D, T, L)
    for i in range(D):
        print(a[i])

if __name__ == '__main__':
    main()
