#!/usr/bin/env python3
# from typing import *

MOD = 998244353

# def solve(a: str, b: str, c: List[str], d: List[str], e: List[str], f: List[str]) -> Any:
def solve(a, b, c, d, e, f):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    a = next(tokens)
    b = next(tokens)
    c = [None for _ in range(a)]
    d = [None for _ in range(a)]
    e = [None for _ in range(b)]
    f = [None for _ in range(b)]
    for i in range(a):
        c[i] = next(tokens)
    for i in range(a):
        d[i] = next(tokens)
    for i in range(b):
        e[i] = next(tokens)
        f[i] = next(tokens)
    assert next(tokens, None) is None
    ans = solve(a, b, c, d, e, f)
    print(ans)  # TODO: edit here

if __name__ == '__main__':
    main()
