#!/usr/bin/env python3
# from typing import *

MOD = 1000000007

# def solve(N: int, M: int, L: int) -> int:
def solve(N, M, L):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M, L = map(int, input().split())
    a = solve(N, M, L)
    print(a)

if __name__ == '__main__':
    main()
