#!/usr/bin/env python3
# from typing import *



# def solve(H: int, W: int, N: int, R: List[int], C: List[int], L: List[int]) -> List[str]:
def solve(H, W, N, R, C, L):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    H, W, N = map(int, input().split())
    R = [None for _ in range(N)]
    C = [None for _ in range(N)]
    L = [None for _ in range(N)]
    for i in range(N):
        R[i], C[i], L[i] = map(int, input().split())
    ans = solve(H, W, N, R, C, L)
    for i in range(N):
        print(ans[i])

if __name__ == '__main__':
    main()
