#!/usr/bin/env python3
# from typing import *


# def solve(a: str, b: str, c: str, d: str, e: List[str], f: List[str], g: List[str]) -> Any:
def solve(a, b, c, d, e, f, g):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = input()
    e = [None for _ in range(a)]
    f = [None for _ in range(a)]
    g = [None for _ in range(a)]
    b, c, d = input().split()
    for i in range(a):
        e[i], f[i], g[i] = input().split()
    ans = solve(a, b, c, d, e, f, g)
    print(ans)  # TODO: edit here


if __name__ == '__main__':
    main()
