#!/usr/bin/env python3
# from typing import *



# def solve(X: int, Y: int) -> Tuple[str, str]:
def solve(X, Y):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    X, Y = map(int, input().split())
    A, B = solve(X, Y)
    print(A, B)

if __name__ == '__main__':
    main()
