#!/usr/bin/env python3
# from typing import *



# def solve(N: str, M: str, X: List[str], A: List[str], B: List[str], S: List[str], T: List[str]) -> Any:
def solve(N, M, X, A, B, S, T):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    X = [None for _ in range(0)]
    N, M, X[0] = input().split()
    A = [None for _ in range(M)]
    B = [None for _ in range(M)]
    S = [None for _ in range(M)]
    T = [None for _ in range(M)]
    for i in range(M):
        A[i], B[i], S[i], T[i] = input().split()
    ans = solve(N, M, X, A, B, S, T)
    print(ans)  # TODO: edit here

if __name__ == '__main__':
    main()
