#!/usr/bin/env python3
# from typing import *



# def solve(S: str, Q: int, T: List[str]) -> List[str]:
def solve(S, Q, T):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    Q = int(input())
    T = [None for _ in range(Q)]
    for i in range(Q):
        T[i] = input()
    a = solve(S, Q, T)
    for i in range(Q):
        print(a[i])

if __name__ == '__main__':
    main()
