#!/usr/bin/env python3
# from typing import *



# def solve(H: int, W: int, N: int, a: List[int]) -> Any:
def solve(H, W, N, a):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    H = int(next(tokens))
    W = int(next(tokens))
    N = int(next(tokens))
    a = [None for _ in range(N)]
    for i in range(N):
        a[i] = int(next(tokens))
    assert next(tokens, None) is None
    ans = solve(H, W, N, a)
    print(ans)  # TODO: edit here

if __name__ == '__main__':
    main()
