#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(N: int, M: int, K: int, u: List[int], v: List[int]) -> Tuple[str, List[str]]:
def solve(N, M, K, u, v):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M, K = map(int, input().split())
    u = [None for _ in range(M)]
    v = [None for _ in range(M)]
    for i in range(M):
        u[i], v[i] = map(int, input().split())
    X, e = solve(N, M, K, u, v)
    print(X)
    print(*[e[i] for i in range(X)])


if __name__ == '__main__':
    main()
