#!/usr/bin/env python3
# from typing import *


# def solve(N: int, P: List[int], M: int, a: List[int], b: List[int]) -> Tuple[str, List[str]]:
def solve(N, P, M, a, b):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    P = [None for _ in range(N)]
    for i in range(N):
        P[i] = int(next(tokens))
    M = int(next(tokens))
    a = [None for _ in range(M)]
    b = [None for _ in range(M)]
    for i in range(M):
        a[i] = int(next(tokens))
        b[i] = int(next(tokens))
    assert next(tokens, None) is None
    K, c = solve(N, P, M, a, b)
    print(K)
    print(*[c[i] for i in range(K)])


if __name__ == '__main__':
    main()
