#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py' number_of_test_cases_you_want
import random

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 100)  # TODO: edit here
    print(N)
    for _ in range(N):
        # Generate a random sequence of the digits 0-9
        digits = list(range(10))
        random.shuffle(digits)
        # Yield the 10-digit number as a concatenation of digits
        print(''.join(map(str, digits)))

    

if __name__ == "__main__":
    main()
