#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(T: str) -> Any:
def solve(T):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    T = input()
    ans = solve(T)
    print(ans)  # TODO: edit here


if __name__ == '__main__':
    main()
