#!/usr/bin/env python3
# from typing import *

MOD = 998244353


# def solve(a: int, b: int, C: int) -> Any:
def solve(a, b, C):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a, b, C = map(int, input().split())
    ans = solve(a, b, C)
    print(ans)  # TODO: edit here


if __name__ == '__main__':
    main()
