#!/usr/bin/env python3
# from typing import *



# def solve(N: int, Q: int, a: List[int], b: List[int], d: List[int]) -> List[str]:
def solve(N, Q, a, b, d):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, Q = map(int, input().split())
    a = [None for _ in range(Q)]
    b = [None for _ in range(Q)]
    d = [None for _ in range(Q)]
    for i in range(Q):
        a[i], b[i], d[i] = map(int, input().split())
    s = solve(N, Q, a, b, d)
    print(*[s[i] for i in range(k)])

if __name__ == '__main__':
    main()
