#!/usr/bin/env python3
# from typing import *



# def solve(N: str, c: List[str], a: List[str], b: List[str]) -> Any:
def solve(N, c, a, b):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = next(tokens)
    c = [None for _ in range(N)]
    a = [None for _ in range(N - 1)]
    b = [None for _ in range(N - 1)]
    for i in range(N):
        c[i] = next(tokens)
    for i in range(N - 1):
        a[i] = next(tokens)
        b[i] = next(tokens)
    assert next(tokens, None) is None
    ans = solve(N, c, a, b)
    print(ans)  # TODO: edit here

if __name__ == '__main__':
    main()
