#!/usr/bin/env python3
# from typing import *

MOD = 998244353

# def solve(T: str) -> Tuple[str, List[str]]:
def solve(T):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    T = input()
    a, b = solve(T)
    print(a)
    for i in range(a):
        print(b[i])

if __name__ == '__main__':
    main()
