#!/usr/bin/env python3
# from typing import *

MOD = 998244353

# def solve(N: str, M: str, X: List[List[str]]) -> int:
def solve(N, M, X):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = next(tokens)
    M = next(tokens)
    X = [[None for _ in range(M + N + 4)] for _ in range(M + N + 4)]
    for j in range(N + 4):
        for i in range(M):
            X[i + j][i + j] = next(tokens)
    assert next(tokens, None) is None
    a = solve(N, M, X)
    print(a)

if __name__ == '__main__':
    main()
