#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(a: int, b: int, c: int, d: List[int]) -> List[str]:
def solve(a, b, c, d):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a, b, c = map(int, input().split())
    d = [None for _ in range(c)]
    for i in range(c):
        d[i] = int(input())
    e = solve(a, b, c, d)
    for i in range(a):
        print(e[i])

if __name__ == '__main__':
    main()
