#!/usr/bin/env python3
# from typing import *


# def solve(N: int, A: List[int], B: List[int], Q: int, L: List[int], R: List[int]) -> List[str]:
def solve(N, A, B, Q, L, R):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    A = [None for _ in range(N - 1)]
    B = [None for _ in range(N - 1)]
    for i in range(N - 1):
        A[i], B[i] = map(int, input().split())
    Q = int(input())
    L = [None for _ in range(Q)]
    R = [None for _ in range(Q)]
    for i in range(Q):
        L[i], R[i] = map(int, input().split())
    a = solve(N, A, B, Q, L, R)
    for i in range(Q):
        print(a[i])


if __name__ == '__main__':
    main()
