#!/usr/bin/env python3
# from typing import *


# def solve(K: int, A: int, B: int) -> int:
def solve(K, A, B):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    K = int(input())
    A, B = map(int, input().split())
    a = solve(K, A, B)
    print(a)


if __name__ == '__main__':
    main()
