#!/usr/bin/env python3
# from typing import *



# def solve(N: int, L: int, D: int) -> float:
def solve(N, L, D):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, L, D = map(int, input().split())
    a = solve(N, L, D)
    print(a)

if __name__ == '__main__':
    main()
