#!/usr/bin/env python3
# from typing import *



# def solve(x: int, a: int, b: int) -> str:
def solve(x, a, b):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    x, a, b = map(int, input().split())
    a1 = solve(x, a, b)
    print(a1)

if __name__ == '__main__':
    main()
