#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'


# def solve(M: int, H: int) -> str:
def solve(M, H):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    M, H = map(int, input().split())
    a = solve(M, H)
    print(a)


if __name__ == '__main__':
    main()
