#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(N: int, M: int, S: str, T: str) -> str:
def solve(N, M, S, T):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    S = input()
    T = input()
    a = solve(N, M, S, T)
    print(a)

if __name__ == '__main__':
    main()
