#!/usr/bin/env python3
# from typing import *



# def solve(N: int, M: int) -> Tuple[int, List[int], List[int], List[int]]:
def solve(N, M):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    b, f, g, h = solve(N, M)
    print(b)
    for i in range(b):
        print(f[i], g[i], h[i])

if __name__ == '__main__':
    main()
