#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(A: int, B: int, S: str) -> str:
def solve(A, B, S):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A, B = map(int, input().split())
    S = input()
    a = solve(A, B, S)
    print(a)

if __name__ == '__main__':
    main()
