#!/usr/bin/env python3
# from typing import *



# def solve(X: int, A: int, B: int) -> str:
def solve(X, A, B):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    X, A, B = map(int, input().split())
    a = solve(X, A, B)
    print(a)

if __name__ == '__main__':
    main()
