#!/usr/bin/env python3
# from typing import *



# def solve(N: int, W: int) -> int:
def solve(N, W):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, W = map(int, input().split())
    a = solve(N, W)
    print(a)

if __name__ == '__main__':
    main()
