#!/usr/bin/env python3
# from typing import *



# def solve(r: float, N: int) -> Tuple[int, int]:
def solve(r, N):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    r = float(input())
    N = int(input())
    c, d = solve(r, N)
    print(c, d)

if __name__ == '__main__':
    main()
