#!/usr/bin/env python3
# from typing import *



# def solve(N: int, K: int, h: List[int]) -> int:
def solve(N, K, h):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, K = map(int, input().split())
    h = [None for _ in range(N)]
    for i in range(N):
        h[i] = int(input())
    a = solve(N, K, h)
    print(a)

if __name__ == '__main__':
    main()
