#!/usr/bin/env python3
# from typing import *


# def solve(H: int, W: int, N: int, A: List[int], B: List[int]) -> Tuple[List[str], List[str]]:
def solve(H, W, N, A, B):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    H, W, N = map(int, input().split())
    A = [None for _ in range(N)]
    B = [None for _ in range(N)]
    for i in range(N):
        A[i], B[i] = map(int, input().split())
    a, d = solve(H, W, N, A, B)
    for i in range(N):
        print(a[i], d[i])


if __name__ == '__main__':
    main()
