#!/usr/bin/env python3
# from typing import *



# def solve(H: int, W: int, N: int) -> List[str]:
def solve(H, W, N):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    H, W, N = map(int, input().split())
    a = solve(H, W, N)
    for i in range(H):
        print(a[i])

if __name__ == '__main__':
    main()
