#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(N: str, M: str, u: List[str], v: List[str], K: str, p: List[str], d: List[str]) -> Tuple[str, str]:
def solve(N, M, u, v, K, p, d):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = input().split()
    u = [None for _ in range(M)]
    v = [None for _ in range(M)]
    for i in range(M):
        u[i], v[i] = input().split()
    K = input()
    p = [None for _ in range(K)]
    d = [None for _ in range(K)]
    for i in range(K):
        p[i], d[i] = input().split()
    Yes, S = solve(N, M, u, v, K, p, d)
    print(Yes)
    print(S)

if __name__ == '__main__':
    main()
