#!/usr/bin/env python3
# from typing import *



# def solve(N: str, M: str, D: List[str], A: List[str], B: List[str]) -> Any:
def solve(N, M, D, A, B):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = next(tokens)
    M = next(tokens)
    D = [None for _ in range(N)]
    A = [None for _ in range(M)]
    B = [None for _ in range(M)]
    for i in range(N):
        D[i] = next(tokens)
    for i in range(M):
        A[i] = next(tokens)
        B[i] = next(tokens)
    assert next(tokens, None) is None
    ans = solve(N, M, D, A, B)
    print(ans)  # TODO: edit here

if __name__ == '__main__':
    main()
