#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(N: int, X: int, Y: int, Z: int) -> str:
def solve(N, X, Y, Z):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, X, Y, Z = map(int, input().split())
    a = solve(N, X, Y, Z)
    print(a)

if __name__ == '__main__':
    main()
