#!/usr/bin/env python3
# from typing import *


# def solve(K: str, D: int) -> int:
def solve(K, D):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    K = input()
    D = int(input())
    a = solve(K, D)
    print(a)


if __name__ == '__main__':
    main()
