#!/usr/bin/env python3
# from typing import *


# def solve(N: str, M: str, a: List[str]) -> List[str]:
def solve(N, M, a):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = next(tokens)
    M = next(tokens)
    a = [None for _ in range(M)]
    for i in range(M):
        a[i] = next(tokens)
    assert next(tokens, None) is None
    p = solve(N, M, a)
    print(*[p[i] for i in range(N)])


if __name__ == '__main__':
    main()
