#!/usr/bin/env python3
# from typing import *

MOD = 998244353


# def solve(N: str, M: str, a: List[str], b: List[str]) -> Any:
def solve(N, M, a, b):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = input().split()
    a = [None for _ in range(M)]
    b = [None for _ in range(M)]
    for i in range(M):
        a[i], b[i] = input().split()
    ans = solve(N, M, a, b)
    print(ans)  # TODO: edit here


if __name__ == '__main__':
    main()
