#!/usr/bin/env python3
# from typing import *

MOD = 998244353


# def solve(a: int, b: List[int], c: List[str], d: int) -> List[str]:
def solve(a, b, c, d):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    a = int(next(tokens))
    b = [None for _ in range(a)]
    c = [None for _ in range(a)]
    for i in range(a):
        b[i] = int(next(tokens))
        c[i] = next(tokens)
    d = int(next(tokens))
    assert next(tokens, None) is None
    e = solve(a, b, c, d)
    for i in range(a):
        print(e[i])


if __name__ == '__main__':
    main()
