#!/usr/bin/env python3
# from typing import *


# def solve(X: int) -> Tuple[int, int]:
def solve(X):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    X = int(input())
    A, B = solve(X)
    print(A, B)


if __name__ == '__main__':
    main()
