#!/usr/bin/env python3
# from typing import *



# def solve(S: str) -> Any:
def solve(S):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    S = input()
    ans = solve(S)
    print(ans)  # TODO: edit here

if __name__ == '__main__':
    main()
