#!/usr/bin/env python3
# from typing import *



# def solve(K: int, S: str, T: str) -> float:
def solve(K, S, T):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    K = int(input())
    S = input()
    T = input()
    a = solve(K, S, T)
    print(a)

if __name__ == '__main__':
    main()
