#!/usr/bin/env python3
# from typing import *



# def solve(N: int, T: str) -> Tuple[int, int]:
def solve(N, T):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    T = input()
    x, y = solve(N, T)
    print(x, y)

if __name__ == '__main__':
    main()
