#!/usr/bin/env python3
# from typing import *


# def solve(N: int, S: int, X: str) -> str:
def solve(N, S, X):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    S = int(input())
    X = input()
    a = solve(N, S, X)
    print(a)


if __name__ == '__main__':
    main()
