#!/usr/bin/env python3
# from typing import *



# def solve(X: str, N: int, S: List[str]) -> List[str]:
def solve(X, N, S):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    X = input()
    N = int(input())
    S = [None for _ in range(N)]
    for i in range(N):
        S[i] = input()
    ans = solve(X, N, S)
    for i in range(N):
        print(ans[i])

if __name__ == '__main__':
    main()
