#!/usr/bin/env python3
# from typing import *


# def solve(N: int, M: int, l: List[int], r: List[int], a: List[int]) -> int:
def solve(N, M, l, r, a):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    l = [None for _ in range(M)]
    r = [None for _ in range(M)]
    a = [None for _ in range(M)]
    for i in range(M):
        l[i], r[i], a[i] = map(int, input().split())
    a1 = solve(N, M, l, r, a)
    print(a1)


if __name__ == '__main__':
    main()
