#!/usr/bin/env python3
# from typing import *


# def solve(L: int, R: int) -> Tuple[int, List[int], List[int]]:
def solve(L, R):
    pass  # TODO: edit here


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    L, R = map(int, input().split())
    M, l, r = solve(L, R)
    print(M)
    for i in range(M):
        print(l[i], r[i])


if __name__ == '__main__':
    main()
