#!/usr/bin/env python3
# from typing import *



# def solve(N: int, U: List[int], V: List[int], L: List[int]) -> List[str]:
def solve(N, U, V, L):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    U = [None for _ in range(N - 1)]
    V = [None for _ in range(N - 1)]
    L = [None for _ in range(N - 1)]
    for i in range(N - 1):
        U[i], V[i], L[i] = map(int, input().split())
    ans = solve(N, U, V, L)
    for i in range(N):
        print(ans[i])

if __name__ == '__main__':
    main()
