#!/usr/bin/env python3
# from typing import *



# def solve(a: str, b: str, c: List[str], d: List[str], e: List[List[str]], f: str) -> int:
def solve(a, b, c, d, e, f):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    a = next(tokens)
    b = next(tokens)
    c = [None for _ in range(b)]
    d = [None for _ in range(a)]
    e = [[None for _ in range(a)] for _ in range(a)]
    for i in range(b):
        c[i] = next(tokens)
    for i in range(a):
        d[i] = next(tokens)
        for j in range(i):
            e[i][j] = next(tokens)
    f = next(tokens)
    assert next(tokens, None) is None
    a1 = solve(a, b, c, d, e, f)
    print(a1)

if __name__ == '__main__':
    main()
