#!/usr/bin/env python3
# from typing import *



# def solve(N: int, p: List[int]) -> List[str]:
def solve(N, p):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    p = [None for _ in range(N)]
    for i in range(N):
        p[i] = int(next(tokens))
    assert next(tokens, None) is None
    q = solve(N, p)
    print(*[q[i] for i in range(N)])

if __name__ == '__main__':
    main()
