#!/usr/bin/env python3
# from typing import *



# def solve(M: int, D: List[int]) -> Tuple[int, int]:
def solve(M, D):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    M = int(next(tokens))
    D = [None for _ in range(M)]
    for i in range(M):
        D[i] = int(next(tokens))
    assert next(tokens, None) is None
    a, b = solve(M, D)
    print(a, b)

if __name__ == '__main__':
    main()
